name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      # If not merged yet, apply fix from https://github.com/ScoopInstaller/Scoop/pull/6395 to ignore non-manifest JSON files
      - name: Patch Get-GitChangedFile
        shell: powershell
        working-directory: scoop_core
        run: if (-NOT (git grep 93b9bae33a88ccde6590c4df3f589f47c58a527e)) {
            git remote add --fetch bintoss https://github.com/BinToss/ScoopInstaller.Scoop.git;
            git cherry-pick -n --empty drop 93b9bae
          ;}
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@main
        with:
          modules-to-cache: BuildHelpers
          shell: powershell
      - name: Test Bucket
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
  test_pwsh:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      # If not merged yet, apply fix from https://github.com/ScoopInstaller/Scoop/pull/6395 to ignore non-manifest JSON files
      - name: Patch Get-GitChangedFile
        shell: pwsh
        working-directory: scoop_core
        run: if (!(git grep 93b9bae33a88ccde6590c4df3f589f47c58a527e)) {
            git remote add --fetch bintoss https://github.com/BinToss/ScoopInstaller.Scoop.git;
            git cherry-pick -n --empty drop 93b9bae
          ;}
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@main
        with:
          modules-to-cache: BuildHelpers
          shell: pwsh
      - name: Test Bucket
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
